# Generated by Django 4.1.5 on 2023-01-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='bin timestamp')),
                ('instrument', models.IntegerField(default=0)),
                ('sample_time', models.DateTimeField(db_index=True, verbose_name='sample time')),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('depth', models.FloatField(null=True)),
                ('sample_type', models.CharField(blank=True, max_length=128)),
                ('cruise', models.CharField(blank=True, max_length=128)),
                ('cast', models.CharField(blank=True, max_length=64)),
                ('niskin', models.IntegerField(null=True)),
            ],
        ),
    ]
